apiVersion: apps/v1
kind: Deployment
metadata:
  name: ergo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ergo
  template:
    metadata:
      labels:
        app: ergo
    spec:
      containers:
      - name: ergo
        image: ghcr.io/ergochat/ergo:stable
        ports:
        - containerPort: 6667
        - containerPort: 6697

---
apiVersion: v1
kind: Service
metadata:
  name: ergo
spec:
  selector:
    app: ergo
  ports:
    - name: irc
      port: 6667
      targetPort: 6667
      protocol: TCP
    - name: irc-tls
      port: 6697
      targetPort: 6697
      protocol: TCP
  type: LoadBalancer
