# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ircd.tunnel.threadr.ai
  namespace: ircd
spec:
  secretName: irc-certs
  issuerRef:
    name: threadr-issuer
    kind: ClusterIssuer
  dnsNames:
    - ircd.tunnel.threadr.ai
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth