apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ircd
resources:
  - certificate.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
configMapGenerator:
  - name: irc-config
    options:
      disableNameSuffixHash: true
    files:
      - files/ircd.motd
      - files/ircd.yaml
images:
  - name: ghcr.io/ergochat/ergo
    newTag: latest