# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irc-db
  labels:
    app: irc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
